export const TAG_OPTIONS = [
    "Strings",
    "Sorting",
    "Recursion",
    "Backtracking",
    "Divide and Conquer",
    "Greedy",
    "Dynamic Programming",
    "Graph",
    "Tree",
    "Stack",
    "Heap",
    "Hashing",
    "DFS",
    "BFS",
    "Brute Force",
    "Shortest Path",
    "Linked List",
    "Binary Tree",
    "Trie",
    "Queue",
    "HashMap",
    "Matrix",
    "Number Theory",
    "Probability",
    "Statistics",
    "Geometry",
    "Combinatorics",
    "Multithreading",
    "Parallel Computing",
    "Bit Manipulation",
    "Computational Geometry",
    "Network Flow"
  ];