export const sampleData = [
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Palindrome Number",
    rating: 1500,
    solvedBy: 2345,
    status: "Accepted",
  },
  {
    id: 84,
    title: "ZigZag Conversion",
    rating: 1800,
    solvedBy: 1234,
    status: "Accepted",
  },
  {
    id: 20,
    title: "Longest Palindromic Subsequence",
    rating: 1200,
    solvedBy: 420,
    status: "Accepted",
  },
  {
    id: 84,
    title: "Container with most water",
    rating: 1300,
    solvedBy: 5432,
    status: "Accepted",
  },
];
